### PR TITLE
Nested polymorphic association fix

### PR DESCRIPTION
**Pull request by voyera**
This fork fixes the issue mentionned here: https://github.com/sferik/rails_admin/issues/1338

I'm hoping it can be integrated in the current version of rails_admin.

### CODE REVIEW

**Comment by voyera** [comment]
Seems like this is an overdue and quite easy merge, anything I'm missing @sferik  ?

**Comment by mshibuya** [comment]
We need RSpec tests for this to ensure this fix works properly.

**Comment by ivanovaleksey** [comment]
Hi! Do you still need specs?

**Comment by mshibuya** [comment]
#2110 is already in the master, closing this.

**Pull request closed without merging**
