### PR TITLE
Import custom variables before Bootstrap variables.

### PR DESCRIPTION
**Pull request by johanneskrtek**
Take advantage of the Sass !default flag in order to configure Bootstrap.

### CODE REVIEW

**Comment by mshibuya** [comment]
Merged in, thanks!
It would be great if you could add instruction to [Wiki](https://github.com/sferik/rails_admin/wiki/Theming-and-customization) on how to make use of this change :pray:

**Comment by johanneskrtek** [comment]
Ok, I will add instructions to the wiki one of these days.

**Comment by johanneskrtek** [comment]
Done. (I also updated the broken links to the bootstrap-sass repo.)

**Comment by mshibuya** [comment]
Thanks :smiley:

**Pull request merged**
