### PR TITLE
UUID Type

### LINKED ISSUE #2247: RailsAdmin doesn't support uuid provided by postgres
Unsupported field datatype: uuid

```
RuntimeError (Unsupported field datatype: uuid):
  rails_admin (0.6.7) lib/rails_admin/config/fields/types.rb:12:in `load'
  rails_admin (0.6.7) lib/rails_admin/config/fields.rb:15:in `block in <module:Fields>'
  rails_admin (0.6.7) lib/rails_admin/config/fields.rb:54:in `call'
  rails_admin (0.6.7) lib/rails_admin/config/fields.rb:54:in `block (2 levels) in factory'
  rails_admin (0.6.7) lib/rails_admin/config/fields.rb:54:in `each'
  rails_admin (0.6.7) lib/rails_admin/config/fields.rb:54:in `detect'
  rails_admin (0.6.7) lib/rails_admin/config/fields.rb:54:in `block in factory'
  rails_admin (0.6.7) lib/rails_admin/config/fields.rb:50:in `each'
  rails_admin (0.6.7) lib/rails_admin/config/fields.rb:50:in `factory'
  rails_admin (0.6.7) lib/rails_admin/config/has_fields.rb:130:in `_fields'
  rails_admin (0.6.7) lib/rails_admin/config/has_fields.rb:133:in `_fields'
  rails_admin (0.6.7) lib/rails_admin/config/has_fields.rb:108:in `all_fields'
...
```

### PR DESCRIPTION
**Pull request by barberj**
fixes #2247

### CODE REVIEW

**Comment by mshibuya** [comment]
Test please!

**Comment by barberj** [comment]
Whats the trick to getting a migration to run on Travis?

**Comment by barberj** [comment]
or how do i limit to run only with postgres?

**Comment by mshibuya** [comment]
You don't have to create actual column, testing as a virtual field(a field without column) is enough.
Please refer to:
https://github.com/sferik/rails_admin/blob/master/spec/rails_admin/config/fields/types/json_spec.rb

**Comment by barberj** [comment]
Sorry I don't understand. If i delete 

`spec/dummy_app/db/migrate/20150421000000_add_uuid_field_to_field_tests.rb` and attempt to run spec/rails_admin/config/fields/types/uuid_spec.rb which i initially modeled after https://github.com/sferik/rails_admin/blob/master/spec/rails_admin/config/fields/date_spec.rb#L65 and update the spec i get 

`undefined method `uuid_field=' for #<FieldTest:0x007fc86f7a2d78>`

Not sure how to use parse_input as uuid is a subclass of string and the parse_input returns nil.

**Comment by barberj** [comment]
see if that works...

**Comment by barberj** [comment]
Failing on things external to my work.

rubocop offense:

```
app/helpers/rails_admin/application_helper.rb:154:51: C: Use the new Ruby 1.9 hash syntax.
        content_tag(:a, class: 'dropdown-toggle', :'data-toggle' => 'dropdown', href: '#') { t('admin.misc.bulk_menu_title').html_safe + '<b class="caret"></b>'.html_safe } +
                                                  ^^^^^^^^^^^^^^^^^
297 files inspected, 1 offense detected
```

gem failure:

```
An error occurred while installing mail (2.6.3), and Bundler cannot continue.
Make sure that `gem install mail -v '2.6.3'` succeeds before bundling.
The command "eval bundle install --without development --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}" failed 3 times.
The command "bundle install --without development --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}" failed and exited with 5 during .
```

**Comment by mshibuya** [comment]
Merged in, thanks!

**Comment by barberj** [comment]
Thank you.

**Pull request merged**
