### PR TITLE
Migrating cerulean theme from v2 to v3 and add button to reset all filters on list page

### PR DESCRIPTION
**Pull request by fmh**

### CODE REVIEW

**Comment by mshibuya** [comment]
What's the difference of #2351 and this?

**Comment by fmh** [comment]
Sorry I didnt make a single PR , I forgot to change the two files variables.scss and theming.scss
In this , I added variables.scss file and in other I added theming.scss

**Comment by mshibuya** [comment]
Please make them as a single PR, because merging them individually never makes sense.

**Comment by fmh** [comment]
it's done.

**Comment by mshibuya** [comment]
It's giving a SCSS error:
```
Showing /Users/shibuya/rails/rails_admin/app/views/layouts/rails_admin/application.html.haml where line #8 raised:

Invalid CSS after "  &": expected "{", was "-default {"

"-default" may only be used at the beginning of a compound selector.
  (in /Users/shibuya/rails/rails_admin/app/assets/stylesheets/rails_admin/rails_admin.scss.erb:18)
Extracted source (around line #18):
16
17
18
19
20
21
              
  @include box-shadow(0 1px 10px rgba(0, 0, 0, 0.1));

  &-default {

    .badge {
      background-color: #fff;

Rails.root: /Users/shibuya/rails/rails_admin/spec/dummy_app

Application Trace | Framework Trace | Full Trace
/Users/shibuya/rails/rails_admin/app/assets/stylesheets/rails_admin/themes/cerulean/theming.scss:18
/Users/shibuya/rails/rails_admin/app/assets/stylesheets/rails_admin/rails_admin.scss.erb:99
sass (3.2.19) lib/sass/scss/parser.rb:1147:in `expected'
sass (3.2.19) lib/sass/scss/parser.rb:1085:in `expected'
sass (3.2.19) lib/sass/scss/parser.rb:692:in `block in simple_selector_sequence'
sass (3.2.19) lib/sass/scss/parser.rb:1095:in `throw_error'
sass (3.2.19) lib/sass/scss/parser.rb:692:in `simple_selector_sequence'
sass (3.2.19) lib/sass/scss/parser.rb:640:in `_selector'
sass (3.2.19) lib/sass/scss/parser.rb:619:in `selector'
sass (3.2.19) lib/sass/scss/parser.rb:603:in `selector_sequence'
sass (3.2.19) lib/sass/scss/parser.rb:528:in `ruleset'
sass (3.2.19) lib/sass/scss/parser.rb:591:in `block in declaration_or_ruleset'
sass (3.2.19) lib/sass/scss/parser.rb:1105:in `block in catch_error'
sass (3.2.19) lib/sass/scss/parser.rb:1105:in `catch'
sass (3.2.19) lib/sass/scss/parser.rb:1105:in `catch_error'
sass (3.2.19) lib/sass/scss/parser.rb:591:in `declaration_or_ruleset'
sass (3.2.19) lib/sass/scss/parser.rb:554:in `block_child'
sass (3.2.19) lib/sass/scss/parser.rb:546:in `block_contents'
sass (3.2.19) lib/sass/scss/parser.rb:535:in `block'
sass (3.2.19) lib/sass/scss/parser.rb:529:in `ruleset'
sass (3.2.19) lib/sass/scss/parser.rb:553:in `block_child'
sass (3.2.19) lib/sass/scss/parser.rb:546:in `block_contents'
sass (3.2.19) lib/sass/scss/parser.rb:82:in `stylesheet'
sass (3.2.19) lib/sass/scss/parser.rb:27:in `parse'
sass (3.2.19) lib/sass/engine.rb:342:in `_to_tree'
sass (3.2.19) lib/sass/engine.rb:274:in `to_tree'
sass (3.2.19) lib/sass/tree/visitors/perform.rb:225:in `visit_import'
sass (3.2.19) lib/sass/tree/visitors/base.rb:37:in `visit'
sass (3.2.19) lib/sass/tree/visitors/perform.rb:100:in `visit'
sass (3.2.19) lib/sass/tree/visitors/base.rb:53:in `block in visit_children'
sass (3.2.19) lib/sass/tree/visitors/base.rb:53:in `map'
sass (3.2.19) lib/sass/tree/visitors/base.rb:53:in `visit_children'
sass (3.2.19) lib/sass/tree/visitors/perform.rb:109:in `block in visit_children'
sass (3.2.19) lib/sass/tree/visitors/perform.rb:121:in `with_environment'
sass (3.2.19) lib/sass/tree/visitors/perform.rb:108:in `visit_children'
sass (3.2.19) lib/sass/tree/visitors/base.rb:37:in `block in visit'
sass (3.2.19) lib/sass/tree/visitors/perform.rb:128:in `visit_root'
sass (3.2.19) lib/sass/tree/visitors/base.rb:37:in `visit'
sass (3.2.19) lib/sass/tree/visitors/perform.rb:100:in `visit'
sass (3.2.19) lib/sass/tree/visitors/perform.rb:7:in `visit'
sass (3.2.19) lib/sass/tree/root_node.rb:20:in `render'
sass (3.2.19) lib/sass/engine.rb:315:in `_render'
sass (3.2.19) lib/sass/engine.rb:262:in `render'
sass-rails (4.0.5) lib/sass/rails/template.rb:22:in `evaluate'
tilt (1.4.1) lib/tilt/template.rb:103:in `render'
sprockets (2.12.3) lib/sprockets/context.rb:197:in `block in evaluate'
sprockets (2.12.3) lib/sprockets/context.rb:194:in `each'
sprockets (2.12.3) lib/sprockets/context.rb:194:in `evaluate'
sprockets (2.12.3) lib/sprockets/processed_asset.rb:12:in `initialize'
sprockets (2.12.3) lib/sprockets/base.rb:374:in `new'
sprockets (2.12.3) lib/sprockets/base.rb:374:in `block in build_asset'
sprockets (2.12.3) lib/sprockets/base.rb:395:in `circular_call_protection'
sprockets (2.12.3) lib/sprockets/base.rb:373:in `build_asset'
sprockets (2.12.3) lib/sprockets/index.rb:94:in `block in build_asset'
sprockets (2.12.3) lib/sprockets/caching.rb:58:in `cache_asset'
sprockets (2.12.3) lib/sprockets/index.rb:93:in `build_asset'
sprockets (2.12.3) lib/sprockets/base.rb:287:in `find_asset'
sprockets (2.12.3) lib/sprockets/index.rb:61:in `find_asset'
sprockets (2.12.3) lib/sprockets/bundled_asset.rb:37:in `init_with'
sprockets (2.12.3) lib/sprockets/asset.rb:24:in `from_hash'
sprockets (2.12.3) lib/sprockets/caching.rb:54:in `cache_asset'
sprockets (2.12.3) lib/sprockets/index.rb:93:in `build_asset'
sprockets (2.12.3) lib/sprockets/base.rb:287:in `find_asset'
sprockets (2.12.3) lib/sprockets/index.rb:61:in `find_asset'
sprockets (2.12.3) lib/sprockets/environment.rb:75:in `find_asset'
sprockets (2.12.3) lib/sprockets/base.rb:295:in `[]'
sprockets-rails (2.3.2) lib/sprockets/rails/helper.rb:230:in `lookup_asset_for_path'
sprockets-rails (2.3.2) lib/sprockets/rails/helper.rb:190:in `check_errors_for'
sprockets-rails (2.3.2) lib/sprockets/rails/helper.rb:159:in `block in stylesheet_link_tag'
sprockets-rails (2.3.2) lib/sprockets/rails/helper.rb:158:in `map'
sprockets-rails (2.3.2) lib/sprockets/rails/helper.rb:158:in `stylesheet_link_tag'
/Users/shibuya/rails/rails_admin/app/views/layouts/rails_admin/application.html.haml:8:in `___sers_shibuya_rails_rails_admin_app_views_layouts_rails_admin_application_html_haml___1988588326320576166_70311553582120'
actionview (4.2.3) lib/action_view/template.rb:145:in `block in render'
activesupport (4.2.3) lib/active_support/notifications.rb:166:in `instrument'
actionview (4.2.3) lib/action_view/template.rb:333:in `instrument'
actionview (4.2.3) lib/action_view/template.rb:143:in `render'
actionview (4.2.3) lib/action_view/renderer/template_renderer.rb:66:in `render_with_layout'
actionview (4.2.3) lib/action_view/renderer/template_renderer.rb:52:in `render_template'
actionview (4.2.3) lib/action_view/renderer/template_renderer.rb:14:in `render'
actionview (4.2.3) lib/action_view/renderer/renderer.rb:42:in `render_template'
actionview (4.2.3) lib/action_view/renderer/renderer.rb:23:in `render'
actionview (4.2.3) lib/action_view/rendering.rb:100:in `_render_template'
actionpack (4.2.3) lib/action_controller/metal/streaming.rb:217:in `_render_template'
actionview (4.2.3) lib/action_view/rendering.rb:83:in `render_to_body'
actionpack (4.2.3) lib/action_controller/metal/rendering.rb:32:in `render_to_body'
actionpack (4.2.3) lib/action_controller/metal/renderers.rb:37:in `render_to_body'
actionpack (4.2.3) lib/abstract_controller/rendering.rb:25:in `render'
actionpack (4.2.3) lib/action_controller/metal/rendering.rb:16:in `render'
actionpack (4.2.3) lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
activesupport (4.2.3) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
/Users/shibuya/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
activesupport (4.2.3) lib/active_support/core_ext/benchmark.rb:12:in `ms'
actionpack (4.2.3) lib/action_controller/metal/instrumentation.rb:44:in `block in render'
actionpack (4.2.3) lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
activerecord (4.2.3) lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
actionpack (4.2.3) lib/action_controller/metal/instrumentation.rb:43:in `render'
remotipart (1.2.1) lib/remotipart/render_overrides.rb:14:in `render_with_remotipart'
/Users/shibuya/rails/rails_admin/lib/rails_admin/config/actions/dashboard.rb:33:in `block (2 levels) in <class:Dashboard>'
/Users/shibuya/rails/rails_admin/app/controllers/rails_admin/main_controller.rb:22:in `instance_eval'
/Users/shibuya/rails/rails_admin/app/controllers/rails_admin/main_controller.rb:22:in `dashboard'
actionpack (4.2.3) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
actionpack (4.2.3) lib/abstract_controller/base.rb:198:in `process_action'
actionpack (4.2.3) lib/action_controller/metal/rendering.rb:10:in `process_action'
actionpack (4.2.3) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (4.2.3) lib/active_support/callbacks.rb:115:in `call'
activesupport (4.2.3) lib/active_support/callbacks.rb:115:in `call'
activesupport (4.2.3) lib/active_support/callbacks.rb:553:in `block (2 levels) in compile'
activesupport (4.2.3) lib/active_support/callbacks.rb:503:in `call'
activesupport (4.2.3) lib/active_support/callbacks.rb:503:in `call'
activesupport (4.2.3) lib/active_support/callbacks.rb:88:in `run_callbacks'
actionpack (4.2.3) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (4.2.3) lib/action_controller/metal/rescue.rb:29:in `process_action'
actionpack (4.2.3) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
activesupport (4.2.3) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (4.2.3) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (4.2.3) lib/active_support/notifications.rb:164:in `instrument'
actionpack (4.2.3) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (4.2.3) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
activerecord (4.2.3) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (4.2.3) lib/abstract_controller/base.rb:137:in `process'
actionview (4.2.3) lib/action_view/rendering.rb:30:in `process'
actionpack (4.2.3) lib/action_controller/metal.rb:196:in `dispatch'
actionpack (4.2.3) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
actionpack (4.2.3) lib/action_controller/metal.rb:237:in `block in action'
actionpack (4.2.3) lib/action_dispatch/routing/route_set.rb:76:in `call'
actionpack (4.2.3) lib/action_dispatch/routing/route_set.rb:76:in `dispatch'
actionpack (4.2.3) lib/action_dispatch/routing/route_set.rb:45:in `serve'
actionpack (4.2.3) lib/action_dispatch/journey/router.rb:43:in `block in serve'
actionpack (4.2.3) lib/action_dispatch/journey/router.rb:30:in `each'
actionpack (4.2.3) lib/action_dispatch/journey/router.rb:30:in `serve'
actionpack (4.2.3) lib/action_dispatch/routing/route_set.rb:821:in `call'
rack-pjax (0.8.0) lib/rack/pjax.rb:12:in `call'
dragonfly (1.0.10) lib/dragonfly/middleware.rb:14:in `call'
warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
warden (1.2.3) lib/warden/manager.rb:34:in `catch'
warden (1.2.3) lib/warden/manager.rb:34:in `call'
rack (1.6.4) lib/rack/etag.rb:24:in `call'
rack (1.6.4) lib/rack/conditionalget.rb:25:in `call'
rack (1.6.4) lib/rack/head.rb:13:in `call'
remotipart (1.2.1) lib/remotipart/middleware.rb:27:in `call'
actionpack (4.2.3) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
actionpack (4.2.3) lib/action_dispatch/middleware/flash.rb:260:in `call'
rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call'
actionpack (4.2.3) lib/action_dispatch/middleware/cookies.rb:560:in `call'
activerecord (4.2.3) lib/active_record/query_cache.rb:36:in `call'
activerecord (4.2.3) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
activerecord (4.2.3) lib/active_record/migration.rb:377:in `call'
actionpack (4.2.3) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
activesupport (4.2.3) lib/active_support/callbacks.rb:84:in `run_callbacks'
actionpack (4.2.3) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
actionpack (4.2.3) lib/action_dispatch/middleware/reloader.rb:73:in `call'
actionpack (4.2.3) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
actionpack (4.2.3) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
actionpack (4.2.3) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
railties (4.2.3) lib/rails/rack/logger.rb:38:in `call_app'
railties (4.2.3) lib/rails/rack/logger.rb:20:in `block in call'
activesupport (4.2.3) lib/active_support/tagged_logging.rb:68:in `block in tagged'
activesupport (4.2.3) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (4.2.3) lib/active_support/tagged_logging.rb:68:in `tagged'
railties (4.2.3) lib/rails/rack/logger.rb:20:in `call'
actionpack (4.2.3) lib/action_dispatch/middleware/request_id.rb:21:in `call'
rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
rack (1.6.4) lib/rack/runtime.rb:18:in `call'
activesupport (4.2.3) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
dragonfly (1.0.10) lib/dragonfly/cookie_monster.rb:9:in `call'
rack (1.6.4) lib/rack/lock.rb:17:in `call'
actionpack (4.2.3) lib/action_dispatch/middleware/static.rb:116:in `call'
rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
railties (4.2.3) lib/rails/engine.rb:518:in `call'
railties (4.2.3) lib/rails/application.rb:165:in `call'
rack (1.6.4) lib/rack/lock.rb:17:in `call'
rack (1.6.4) lib/rack/content_length.rb:15:in `call'
rack (1.6.4) lib/rack/handler/webrick.rb:88:in `service'
/Users/shibuya/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
/Users/shibuya/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
/Users/shibuya/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'
```

**Comment by fmh** [comment]
oups, i'll check this tonight.

**Comment by fmh** [comment]
I cannot reproduce this error. It looks like a syntax error.
can your upgrade your saas gem version 
my gems : 
sass (3.4.15, 3.4.14, 3.4.13)  sass-rails (5.0.3, 5.0.1)

Cerulean Theme look without border-radius  : 

capture d ecran 2015-07-03 a 18 14 20

capture d ecran 2015-07-03 a 18 21 04

**Comment by mshibuya** [comment]
Of course I can update sass, but the users may not be able to.
(RailsAdmin officially supports Rails 4.0, which has sass-rails(~> 4.0.0) and sass(~> 3.2.0) dependency by default.)
Can you make this compatible with sass 3.2.x?

**Comment by fmh** [comment]
I'll try this weekend.

**Comment by fmh** [comment]
it's better with the old syntax 😉 and some colors adapted

**Comment by fmh** [comment]
with reset filters button
before click on remove filters button
capture d ecran 2015-07-18 a 03 11 50
init state or after click on remove filters button 
capture d ecran 2015-07-18 a 03 12 13

**Comment by mshibuya** [comment]
Merged in, thanks! :smiley:

**Pull request merged**
