### PR TITLE
Move hash symbolizer into a helper, prevent namespace conflicts

### PR DESCRIPTION
**Pull request by zapnap**
See #2387

### CODE REVIEW

**Comment by mshibuya** [comment]
Rubocop check failed, can you fix it?

**Comment by zapnap** [comment]
Will take a look shortly, thanks. (Traveling today so internet is a bit
spotty)

pls excus typos. im mobile.

**Comment by zapnap** [comment]
There we go!

**Comment by zapnap** [comment]
ty

**Pull request merged**
