### PR TITLE
Replacing sass-rails with sassc-rails

### PR DESCRIPTION
**Pull request by MikeRogers0**
Following up for https://github.com/sferik/rails_admin/pull/3072

This replaces `sass-rails` with `sassc-rails`, as `sass-rails` is now just a wrapper for `sassc-rails` (as updated in https://github.com/rails/sass-rails/pull/424 )

### CODE REVIEW

**Comment by MikeRogers0** [comment]
It looks like CI is failing, but I'm seeing the same error locally in the `master` branch. @sferik can you shed some light on what's up?

**Comment by jasnow** [comment]
FYI: Change 
s/10/11/ on line 44 and 
s/20/21/  on line 45 
in inspec/integration/basic/dashboard/rails_admin_basic_dashboard_spec.rb
makes my local build green. Now figure out why. My run line:
```
bundle exec rspec ./spec/integration/basic/dashboard/rails_admin_basic_dashboard_spec.rb:36
```

**Comment by mshibuya** [comment]
Failure was an timing issue, that spec fails during specific window of time in UTC.

**Comment by MikeRogers0** [comment]
Thank you @mshibuya, that looks to have fixed it :)

**Comment by mshibuya** [comment]
Lowering [coverage-threshold](https://github.com/sferik/rails_admin/blob/master/spec/spec_helper.rb#L15) to 90.05 is acceptable, since this change should not harm test exhaustivity.

**Comment by MikeRogers0** [comment]
@mshibuya https://travis-ci.org/sferik/rails_admin/jobs/549623012 is returning:

> Coverage (90.05%) is below the expected minimum coverage (90.08%).

Do you know how I change the minimum coverage?

**Comment by MikeRogers0** [comment]
@mshibuya Minimum coverage updated 🤞 :)

**Comment by MikeRogers0** [comment]
Yay all green 🎊

**Comment by mshibuya** [comment]
Merged in, thanks ❤️

**Pull request merged**
