### PR TITLE
Fix: filter search box duplication issue.

### PR DESCRIPTION
**Pull request by vrushalip**
Added condition while appending filter box.

### CODE REVIEW

**Comment by ether1984** [comment]
it won't work for select tag in filter search box

**Comment by ether1984** [comment]
var $content = $('<p id="' + field_name + '">')
                .addClass('filter form-search')
                .append('<span class="label label-info form-label"><a href="#delete" class="delete"><i class="fa fa-trash-o fa-fw icon-white"></i>' + field_label + '</a></span>')
                .append('&nbsp;' + control + '&nbsp;' + (additional_control || ''));
if ($('p#' + field_name).length == 0) {
    $('#filters_box').append($content);
}

**Comment by evanboho** [comment]
I did not see this PR and fixed the same bug in https://github.com/sferik/rails_admin/pull/2998

**Comment by mshibuya** [comment]
Fixed by #2998.

**Pull request closed without merging**
