### PR TITLE
Switch to sassc-rails as Ruby Sass is deprecated

### PR DESCRIPTION
**Pull request by MikeRogers0**
https://github.com/sass/ruby-sass Ruby Sass is deprecated and will be unmaintained as of 26 March 2019.

This switches the `sass-rails` gem over to `sassc-rails` ( https://github.com/sass/sassc-rails ) .

### CODE REVIEW

**Comment by MikeRogers0** [comment]
CI appears to be breaking after I branched off master 😯 Anyone know how I can fix? @sferik

**Comment by riouruma** [comment]
any updates?

**Comment by MikeRogers0** [comment]
@riouruma I'm also curious as to what I can do to help get this in :)

**Comment by itoyama** [comment]
@MikeRogers0 You should pull master. That resolves fatal errors of CI.

**Comment by MikeRogers0** [comment]
Merged master & also updated the `Gemfile` with include the new replacement gem. I'm still seeing failures :/

**Comment by itoyama** [comment]
Some of errors may be resolved by below.
`gem 'sqlite3', '>= 1.3'` -> `gem 'sqlite3', '~> 1.3'` in `Gemfile`

Reason:
 https://travis-ci.org/sferik/rails_admin/jobs/489587773#L661
 https://rubygems.org/gems/sqlite3
> 1.4.0 - February 04, 2019 (68.5 KB)

**Comment by MikeRogers0** [comment]
I'm struggling a bit with this :/ Anyone else want take over this PR? // @itoyama

**Comment by peret** [comment]
Hi, I'm a little confused by the changes of this PR. Looking at https://github.com/sferik/rails_admin/pull/3072/files, it seems like you are _adding_ sassc-rails, but sass-rails is also still in there. I think that might be what's causing the conflicts in the CI?
Can you double-check your commits to make sure you are replacing the sass-rails gem?

**Comment by MikeRogers0** [comment]
I think this has been fixed upstream https://github.com/rails/sass-rails/pull/424 - I think I can close this PR off now.

**Comment by jasnow** [comment]
@MikeRogers0  - Think you can reopen this item again because sassc-rails gem appears to be a drop in replacement for sass-rails gem. FYI

**Comment by rlgreen91** [comment]
What is the status of this change?  I know that sass-rails is supposed to be switching to sassc in version 6, but it's unclear when that upgrade will be coming and EOL was back in March.

**Comment by mshibuya** [comment]
@rlgreen91  #3156 is in place now.

**Pull request closed without merging**
