### PR TITLE
Fixed filter by enum filter when label <> value

### PR DESCRIPTION
**Pull request by mshytikov**
Refactored code to remove unnecessary calls to `parse_value`.
Which were affecting filter by enum (rails >= 5.0):
If enum defined like
```
enum size: { L: 'l', S: 's' }
```
Due to multiple calls, the chain when filtering by size is following:
```
parse_value("l") => "L"
parse_value("L") => nil
```
Which leads to non working filtering.
NOTE: `parse_value` returns correct result in both cases above

### CODE REVIEW

**Comment by mshibuya** [comment]
Could you add a test case for that issue?

**Comment by mshytikov** [comment]
Sure, I will add tests.
(need to find some time, should be ready in few days. )

**Comment by mshytikov** [comment]
work in progress.

**Comment by mshytikov** [comment]
Turns out that fix provided in #2952 for `active_record_enum.rb` is also required to pass the build for some older rails versions

**Comment by mshytikov** [comment]
@mshibuya I have added tests. And have rebased them, so it is possible to see in travis logs that without fix they are failing. 
I was quite unlucky with this PR that I also faced `pg` update see the last commit message. 
Could you please review PR ?

**Comment by mshibuya** [comment]
Merged in 857696119c70e6603fa7de0dca8b983ba01c5195, thanks so much!

**Comment by mshytikov** [comment]
👍  thank you.

**Pull request closed without merging**
