### PR TITLE
Fix hidden indent

### PR DESCRIPTION
**Pull request by jubilee2**
it is fix hidden field layout under create and edit pages!
https://github.com/sferik/rails_admin/issues/2487

### CODE REVIEW

**Comment by jubilee2** [comment]
anyone know how to fix travis test

**Comment by prem-prakash** [comment]
@jubilee2 it seems to be a random error, did you try to rerun the build?

**Comment by jubilee2** [comment]
> @jubilee2 it seems to be a random error, did you try to rerun the build?

do you mean travis?

**Comment by prem-prakash** [comment]
> > @jubilee2 it seems to be a random error, did you try to rerun the build?
> 
> do you mean travis?

Yeah, I mean travis. I am not sure if you or anyone is allowed to, using their web interface. If you are not allowed you can try sending an empty commit to trigger a new build.

But I was taking a look at others open PRs in this repo, I noticed that there are many with random errors on travis. So maybe there is a systematic issue.

**Comment by jubilee2** [comment]
> > > @jubilee2 it seems to be a random error, did you try to rerun the build?
> > 
> > 
> > do you mean travis?
> 
> Yeah, I mean travis. I am not sure if you or anyone is allowed to, using their web interface. If you are not allowed you can try sending an empty commit to trigger a new build.
> 
> But I was taking a look at others open PRs in this repo, I noticed that there are many with random errors on travis. So maybe there is a systematic issue.
@prem-prakash 
that is JRuby error i just updated JRuby version #3311

**Comment by mshibuya** [comment]
Thanks for the fix!

**Pull request merged**
