### PR TITLE
Support translation for active record enum type

### PR DESCRIPTION
**Pull request by ivanzotov**
How about support translations for ActiveRecord enum?

Example:

```
en:
  enums:
    model_name:
       enum_field_name:
          enabled: Enabled
          disabled: Disabled
          ...

```

### CODE REVIEW

**Comment by yurijmi** [comment]
What would be awesome!

**Comment by yurijmi** [comment]
This works. Gotta use @ivanzotov repo in Gemfile for now. Thanks, Ivan.

**Comment by ivanzotov** [comment]
@yurijmi You are welcome!

**Comment by k0kubun** [comment]
I got an error like `NoMethodError: undefined method `invert' for #<Array:0x00000008183c30>` around enum and this branch fixed it. I want this patch to be merged.

**Comment by mshibuya** [comment]
Looks nice, can be merged in after specs are added and conflict is resolved.

**Comment by mshibuya** [comment]
Please reopen on update.

**Pull request closed without merging**
