### PR TITLE
Issue #1434 filter functionality for has many association.

### PR DESCRIPTION
**Pull request by barsukov**
This commit has few changes : 
1) I implement filter functionality for has_many association with issue #1434
2) I refactor one spec with rspec best practices and factory girl too.

### CODE REVIEW

**Comment by rafaelgonzalez** [comment]
@bbenezech 

It makes sense to me to have a HM or HABTM filter.

I have a `Project` model with many `Task` and want to be able to filter out projects with tasks with a specific name, or a name that has certain content. (in truth it is really a HABTM relationship in my case, so I would like to filter all the projects that have the same task assigned to them but I use `has_many :through` with an intermediate model)

Please see #1434 were a partial solution has been discussed.

**Comment by barsukov** [comment]
I think this is not actual anymore?

**Comment by rafaelgonzalez** [comment]
Well the solution I use in #1434 only partially solves my problem (see my comment above), so to me this is still actual.

**Comment by mshibuya** [comment]
The same as #1363.

**Pull request closed without merging**
