### PR TITLE
Added the ability to rollback/revert PaperTrail version history. Includes change previewing.

### PR DESCRIPTION
**Pull request by rikkipitt**
This pull request solves #1857. It gives the user the ability to preview and revert the changes recorded with [PaperTrail](https://github.com/airblade/paper_trail).

A jQuery html diff'ing plugin was added to help visualise the version changes. The preview works on the rails_admin dashboard, history_index and history_show views and appears in a modal (see screenshots below).

I feel it adds much needed (and lacking) functionality and finishes off the auditing nicely. Please test and let me know what you think!

To-dos:

- [x] Remove modal table [column width](https://github.com/sferik/rails_admin/wiki/List-view-table-styling) limit as it cuts off content on longer lines. **Edit: was actually css based, extra commit fixes this below**

history
modal

### CODE REVIEW

**Comment by mshibuya** [comment]
Looks promising.
But to merge this in, we have to consider several issues:
- must be fully covered by tests
- need to work harmlessly with [internal audit plugin](https://github.com/sferik/rails_admin/wiki/Internal-audit-plugin)

Instead, could you consider implementing this as [RailsAdmin plugin](https://github.com/sferik/rails_admin/wiki#plugins)? I'm not quite sure if everyone who uses RailsAdmin will need this rollback feature...

**Comment by rikkipitt** [comment]
Hi @mshibuya, thanks for your feedback. Admittedly, tests are lacking. I thought the internal auditing was being phased out? Either way, I think this is a logical addition (even if it is a plugin). It makes sense to be able to actually use the history, especially in a more visual manner.

I'm currently working on another plugin, so I might convert this over to it's own too. I'll keep you posted.

**Comment by rikkipitt** [comment]
Plugin created! I'll release it and close this pull request. May I add it to the wiki when it's released\?

**Comment by mshibuya** [comment]
Great! :beers:

**Pull request closed without merging**
