### PR TITLE
Use RailsAdmin.I18n for multiselect translations

### PR DESCRIPTION
**Pull request by zaknafain**
**Problem:**
I tried to translate a custom action into German but had problems translating the multi select.
I found out that the English words were hard coded.
There was also a placeholder in the search form, that was reading undefined.

**Solution:**
I replaced the hard coded English words with the already used RailsAdmin.I18n.t function and moved them to the en.yml.
I added a translation for the undefined search form placeholder.

### CODE REVIEW

**Comment by zaknafain** [comment]
Sadly there is an `Error in `/usr/lib/jvm/java-8-oracle/bin/java': double free or corruption (out)` error for jruby.
I never worked with jruby but I am pretty sure, that this is not a result of my changes.

**Comment by zaknafain** [comment]
I had to update the version of jruby to fix the error mentioned above.

**Comment by jubilee2** [comment]
> I had to update the version of jruby to fix the error mentioned above.
> This would close #3311

thank you! i am out

**Comment by mshibuya** [comment]
Translations are already passed to JS [here](https://github.com/sferik/rails_admin/blob/master/app/views/rails_admin/main/_form_filtering_multiselect.html.haml#L31-L38), though it does not include `add` and `remove` keys...
Please try with community-provided translations.
https://github.com/sferik/rails_admin/wiki/Translations

**Pull request closed without merging**
