### PR TITLE
Fix: remove wrong class `.image_field`

### PR DESCRIPTION
**Pull request by dalpo**
I made a mistake adding the class `.image_field` which is related to a table column `image`.

### CODE REVIEW

**Comment by dalpo** [comment]
https://github.com/sferik/rails_admin/commit/e79b8ab5cc26d970c4e615740237c26ebc3df397#diff-650cebc4346976571db9fc5f9c8127d5R65

**Comment by dalpo** [comment]
@mshibuya Could you merge please?

The issue is present for each `file` field which name is not `image`

**Comment by mshibuya** [comment]
I'm sorry for delay, thanks!

**Comment by dalpo** [comment]
Thanks to you @mshibuya and for all the work done! :wink:

**Pull request merged**
