### PR TITLE
dependent_field for belongs_to

### PR DESCRIPTION
**Pull request by fantgeass**
Dependent field for belongs_to association.

Example:

We have user with country/city.
User chooses country "Russia" and city field now contains all russian cities.
When user changes country  to "France", city field will lost value and select list now contain all "France" cities.
~~~
class User < ActiveRecord::Base
	belongs_to :country
	belongs_to :city

	rails_admin do
		edit do
		  field :city do
		    dependent_field :country
		    associated_collection_scope do
		      country_id = bindings[:controller].params[:dependent_field_value]
		      Proc.new { |scope|
		        scope = scope.where(country_id: country_id) if country_id
		      }
		    end
		  end
		end
  end
end
~~~

### CODE REVIEW

**Comment by mshibuya** [comment]
Please add some tests.

**Comment by SuperMasterBlasterLaser** [comment]
This feature seems to be very useful. I solved it by creating custom javascript code that will filter autocomplete values depending on value of other select. Also this required to me to create controller.

**Comment by SuperMasterBlasterLaser** [comment]
@fantgeass Does this dependent_field work with `has_and_belongs_to_many` association where filtering multiselect will be?

**Comment by chrisbloom7** [comment]
I came up with an [alternative solution that wasn't too involved](http://www.christopherbloom.com/2014/09/04/dynamic-enum-fields-in-nested-association-forms-in-rails-admin/). Having it baked in to RA as an option would be very useful, but my approach isn't that much more work and allows you to programmatically determine what subitems should be displayed beyond simply filtering.

**Comment by SuperMasterBlasterLaser** [comment]
@chrisbloom7 This solution works well, but it is for specific conditions. You can create your own controller that interracts with `ui,js` javascript code.

However, we need universal filtering, which will be configured via `field` in `rails_admin.rb`. It must be able to work with any `has_many` and `has_and_belongs_to_many` associations. Also it must not require additional controller from user.

**Comment by chrisbloom7** [comment]
@SuperMasterBlasterLaser agreed. Was just listing an alternative for those looking to do so before it's part of RA core functionality.

**Comment by bbenezech** [comment]
IMO this should not be part of RA core.
This is way too specific, sorry.

**Pull request closed without merging**
