### PR TITLE
Fix: better html markup for input fields

### PR DESCRIPTION
**Pull request by dalpo**

### CODE REVIEW

**Comment by dalpo** [comment]
The PR is ready!

######Before:
screenshot from 2015-06-19 19 01 02

######After:
screenshot from 2015-06-19 19 00 11

**Comment by rikkipitt** [comment]
Looks great, much needed fix to bring this field type up to date with Bootstrap standards.

**Comment by luizpicolo** [comment]
+1

**Comment by mshibuya** [comment]
:+1: Thanks!

**Pull request merged**
