### PR TITLE
Fixing sprockets wysihtml5 problem (2)

### PR DESCRIPTION
**Pull request by AlexEscalante**
This works but labels are missing from some toolbar buttons. I guess this is another issue to look into.

### CODE REVIEW

**Comment by luizpicolo** [comment]
I'm experiencing this problem as well. Good job. :+1:

**Comment by mshibuya** [comment]
Asset alias check has been reverted by rails/sprockets-rails#251.
Using the master of sprockets-rails works now.
```ruby
gem 'sprockets-rails', github: 'rails/sprockets-rails'
```

**Comment by luizpicolo** [comment]
Thats good. resolved my problem. Thanks :+1:

**Comment by vorant94** [comment]
Does anybody have another solution? Because It crashes with using compass-rails gem
````
Bundler could not find compatible versions for gem "sprockets":
  In Gemfile:
    compass-rails (>= 0) ruby depends on
      sprockets (< 2.13) ruby

    sprockets-rails (>= 0) ruby depends on
      sprockets (3.0.0)
````

**Pull request closed without merging**
