### PR TITLE
Add instance option to append a CSS class for rows

### PR DESCRIPTION
**Pull request by MrOutis**
As Rails Admin uses Bootstrap, I wanted to use the table's contextual classes in my lists.
This is an approach to implement that using a method declared in RailsAdmin::Config, it has access to the object being rendered into the row.
### Usage

``` ruby
RailsAdmin.config do |config|
config.model Event do
  list do
    row_css_class do
      bindings[:object].mode == 'panic' ? 'danger' : 'success'
    end
end
```

### CODE REVIEW

**Comment by mshibuya** [comment]
Test needed!

**Comment by MrOutis** [comment]
indeed, I'll add them soon, @mshibuya; however, do you find it helpful?
I really don't know if there's a better/cleaner way to implement this.

**Comment by mshibuya** [comment]
I think this is okay, it's simple and useful 😃

**Comment by MrOutis** [comment]
@mshibuya, I will close this PR in favour of #2860.
It will be great if you can give me another review (after almost 1 year, hehe)

**Pull request closed without merging**
