### PR TITLE
Fix regexp for converting rails date format to momentjs

### PR DESCRIPTION
**Pull request by prem-prakash**
Addresses #982

### CODE REVIEW

**Comment by mshibuya** [comment]
Please do not open&close PR repeatedly. If you find problem with your PR, just push new commit to original branch(then your PR will be updated).

Additionally, can you write some specs for this fix?

**Comment by prem-prakash** [comment]
Sorry for that. Yes I will write some specs.

Em dom, 1 de nov de 2015 08:06, Mitsuhiro Shibuya <notifications@github.com>
escreveu:

**Comment by prem-prakash** [comment]
@mshibuya test added

**Comment by mshibuya** [comment]
Nice :heart: 
One more thing left, please resolve rubocop check failure!

**Comment by prem-prakash** [comment]
@mshibuya done :+1:

**Comment by mshibuya** [comment]
Thank you :heart_eyes:

**Pull request merged**
