### PR TITLE
Add Neo4j support

### PR DESCRIPTION
**Pull request by djvs**

### CODE REVIEW

**Comment by prem-prakash** [comment]
@djvs what this PR makes?

**Comment by mshibuya** [comment]
Wow! This PR adds Neo4j support, it's surprising 🎉 
So sorry for kept you waiting, but I'm eager to merge this PR. Please give me a little time to review this.

**Comment by mshibuya** [comment]
@cheerfulstoic This work seems to be done mainly by you, although @djvs has opened this PR.
Is it okay for you to integrate your work into RailsAdmin?

Looks like some extra work is needed to merge this, but I want to try if it is possible.

**Comment by djvs** [comment]
> @cheerfulstoic This work seems to be done mainly by you, although @djvs has opened this PR.
> Is it okay for you to integrate your work into RailsAdmin?
> 
> Looks like some extra work is needed to merge this, but I want to try if it is possible.

My company commissioned this work a few years back.  Please feel free to use assuming @cheerfulstoic approves.

**Comment by cheerfulstoic** [comment]
Yeah, absolutely feel free to use it

**Comment by mshibuya** [comment]
Looks like we need some more work to make this fully functional, so I've merged this into separate branch `neo4j`.
Thanks a lot for your contribution!

**Pull request merged**
