### PR TITLE
Improve form margins

### PR DESCRIPTION
**Pull request by tagliala**
Do you have a comprehensive form with all kind of fields to perform a visual test?

### Before

old

### After

new

### CODE REVIEW

**Comment by dalpo** [comment]
:+1:

**Comment by mshibuya** [comment]
Thanks :+1:

**Comment by tagliala** [comment]
@mshibuya you're welcome!

Have you done a comprehensive test with different inputs?

**Comment by mshibuya** [comment]
No, I've just trusted your work ;)

**Comment by tagliala** [comment]
@mshibuya please mention me if there are any issues caused by this PR, I will be glad to help

**Pull request merged**
