### PR TITLE
Fix sidebar and main content style

### PR DESCRIPTION
**Pull request by tagliala**
This is my first PR to Rails Admin.

Sorry if this is a duplicate

# Before:
screen shot 2015-04-09 at 16 30 32
(*please notice the horizontal scrollbar*)

screen shot 2015-04-09 at 16 31 27
(*please notice the horizontal scrollbar*)

# After
screen shot 2015-04-09 at 16 29 09
screen shot 2015-04-09 at 16 29 02

### CODE REVIEW

**Comment by tagliala** [comment]
Failures seem not related to my change

**Comment by sferik** [comment]
I fixed the build in `master`. Would you mind rebasing and force pushing to force Travis to rebuild?

**Comment by tagliala** [comment]
The failure still seems unrelated. It depends on the order of the tests, take a look at the seed:

```sh
$ CI_ORM=mongoid rspec --seed 60737
Run options: exclude {:skip_mongoid=>true, :active_record=>true}

Randomized with seed 60737
..............................................................................................................................................................................................................................................F...............................................................................................................................................................................................................................................................................................................................................

Failures:

  1) RailsAdmin Config DSL List Section items' fields has option to customize output formatting
     Failure/Error: expect(find('tbody tr:nth-child(1) td:nth-child(3)')).to have_content(@fans[1].name.upcase)
       expected #has_content?("FAN 8") to return true, got false
```

```sh
$ CI_ORM=mongoid rspec --seed 60738
Run options: exclude {:skip_mongoid=>true, :active_record=>true}

Randomized with seed 60737
..............................................................................................................................................................................................................................................F...............................................................................................................................................................................................................................................................................................................................................

Failures:

  1) RailsAdmin Config DSL List Section items' fields has option to customize output formatting
     Failure/Error: expect(find('tbody tr:nth-child(1) td:nth-child(3)')).to have_content(@fans[1].name.upcase)
       expected #has_content?("FAN 8") to return true, got false
     # ./spec/integration/config/list/rails_admin_config_list_spec.rb:310:in `block (3 levels) in <top (required)>'

Finished in 50.01 seconds (files took 3.35 seconds to load)
574 examples, 1 failure

Failed examples:

rspec ./spec/integration/config/list/rails_admin_config_list_spec.rb:295 # RailsAdmin Config DSL List Section items' fields has option to customize output formatting

Randomized with seed 60737

```sh
$ CI_ORM=mongoid rspec --seed 60738
Run options: exclude {:skip_mongoid=>true, :active_record=>true}

Randomized with seed 60738
..............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

Finished in 50.06 seconds (files took 3.2 seconds to load)
574 examples, 0 failures
```

**Comment by tagliala** [comment]
ping

**Comment by mshibuya** [comment]
Thanks!

**Comment by tagliala** [comment]
:+1: you're welcome! thank you!

**Pull request merged**
