### PR TITLE
Issue #1099: Filtering on "Is present" and "Is blank" on boolean columns

### PR DESCRIPTION
**Pull request by HashNotAdam**
Filtering a boolean field on "Is present" or "Is blank" produces SQL that
includes checking against an empty string. Since a boolean field can only be
true, false, or null, this causes errors in some databases.

Remove the empty string search for boolean field types.

### CODE REVIEW

**Comment by HashNotAdam** [comment]
CI failing due to Rubocop issues addressed in [PR 2679](https://github.com/sferik/rails_admin/pull/2679)

**Comment by mshibuya** [comment]
Test needed!

**Comment by HashNotAdam** [comment]
Come on! The original code isn't tested... how about you test the existing functionality and I'll test the micro-change in this PR and keep using my fork in the mean-time? :P

**Comment by mshibuya** [comment]
The original code is tested here,
https://github.com/sferik/rails_admin/blob/master/spec/rails_admin/adapters/active_record_spec.rb#L188-L198
just adding a few examples is enough. This is important to make sure the code you wrote won't break in the future.

**Comment by HashNotAdam** [comment]
I've updated those tests but that is both nasty and terribly smelly. The fact that changing the code didn't cause a test to break tells you it wasn't properly tested.

There is no testing for the class itself, just the output after running through a module and two classes. If you are lucky enough for a future change to break the test, there will still be some analysis to work out where the issue exists. Even having 2 classes nested inside that module with module methods and classes mixed together is horrible and it makes it harder to find what you are looking for.

**Comment by mshibuya** [comment]
I clearly state that horrible tests are better than no tests at all.
I know there's so many not-so-good things in the codebase, and since this is an open source software, it's everybody's job to improve them.

Thank you for your work, I really appreciate it 😃

**Pull request merged**
