### PR TITLE
Better time field support

### PR DESCRIPTION
**Pull request by dalpo**

### CODE REVIEW

**Comment by dalpo** [comment]
(related to https://github.com/sferik/rails_admin/pull/2391)

### RFC: How should be saved a time input type?

**Comment by fmh** [comment]
thx, once merged, i'll test and tell you if ok. thx

**Comment by dalpo** [comment]
I'm going to split this commits into more PRs

**Comment by fmh** [comment]
Hello,
any news ? I was absent and have not followed RA evolution :(
thx

**Pull request closed without merging**
