### PR TITLE
Improve navigation sidebar

### LINKED ISSUE #2279: Improve navigation bar
Hi, IMHO the navigation bar could be slightly improved. 

are you interested in the following PR ?

### Before and After
screen shot 2015-04-29 at 12 15 27

### PR DESCRIPTION
**Pull request by tagliala**
Fix #2279

### Some Screenshots
screen shot 2015-04-30 at 15 05 08
(small screens... should be collapsed, but with this PR it is far better than before)

screen shot 2015-04-30 at 15 05 40

screen shot 2015-04-30 at 15 06 24

### CODE REVIEW

**Comment by tagliala** [comment]
Could you please re-run the travis build?

**Comment by sferik** [comment]
Okay, I just restarted the two jobs that failed.

**Comment by tagliala** [comment]
there is another job failing but it seems unrelated

**Comment by tagliala** [comment]
@sferik I'm getting this error on the master branch too

```sh
rails_admin on master $ RAILS_VERSION=4.0 CI_ORM=active_record CI_DB_ADAPTER=sqlite3 rspec --seed 18181
Run options: exclude {:mongoid=>true, :skip_active_record=>true}

Randomized with seed 18181
......................................................................................................................................................................................................................................................................................................................F.............................................................................................................................................................................................................................................................................

Failures:

  1) RailsAdmin secondary navigation does not cause error when email is nil
     Failure/Error: visit dashboard_path
     NoMethodError:
       undefined method `_run__1516910587489711875__find__callbacks' for #<User::Confirmed:0x007f944f4a2000>

```

**Comment by tagliala** [comment]
Could you please re-run the travis build?

**Comment by sferik** [comment]
@tagliala It’s running now.

**Comment by tagliala** [comment]
Found some offenses but they are not depending on my PR

**Comment by dalpo** [comment]
:+1:

**Comment by mshibuya** [comment]
Thanks!

**Comment by tagliala** [comment]
:+1:

**Pull request merged**
