### PR TITLE
Fix Rubocop violations

### PR DESCRIPTION
**Pull request by nard-tech**
In #3221, Travis CI failed due to Rubocop offenses.
In addition, violations ignored by `.rubocop_todo.yml` have been left alone long time.
I fixed  these violations mainly using `rubocop -a`.

### CODE REVIEW

**Comment by nard-tech** [comment]
@mshibuya Travis CI failed in Ruby version 2.2 due to SyntaxError like this:

```
An error occurred while loading ./spec/controllers/rails_admin/application_controller_spec.rb.
Failure/Error: require 'rspec/rails'
SyntaxError:
  /home/travis/build/sferik/rails_admin/vendor/bundle/ruby/2.2.0/gems/rspec-rails-4.0.0/lib/rspec/rails/example/mailer_example_group.rb:25: syntax error, unexpected '.'
            options&.each { |key, value| default_u...
                     ^
```
Safe navigation operator with `&` is added since Ruby 2.3, so Ruby 2.2 raises SyntaxError.

Which is the best way to resolve this error?
*   drop support for Ruby 2.2 from RailsAdmin
*   specify another version of rspec-rails in Ruby 2.2

**Comment by prem-prakash** [comment]
I would vote to drop support for Ruby 2.2 from RailsAdmin

**Comment by mshibuya** [comment]
In the next major release of RailsAdmin I will drop support for Ruby older than 2.5.0. Please hold on until 3.0.0 development is ready.

**Comment by mshibuya** [comment]
The master branch is ready, can you rebase this to it?

**Comment by mshibuya** [comment]
Closing this because it will not be able to merged cleanly with the fix I made in the master https://github.com/sferik/rails_admin/commit/43794519dd011a6db2198c31c6effa48953e5c4d . 
I'm sorry that I prioritized mine, but I needed it for https://github.com/sferik/rails_admin/commit/01e8d5fc8ec94e68af6fdbd80759a751cd83f74a 🙇

**Pull request closed without merging**
